-- CUSTOMER ID
CREATE SEQUENCE cust_id_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    NO CYCLE
    CACHE 1;

-- ORDER ID
CREATE SEQUENCE od_id_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    NO CYCLE
    CACHE 1;

-- SHOPPING CART ID
CREATE SEQUENCE shop_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    NO CYCLE
    CACHE 1;

-- BOOK ID
CREATE SEQUENCE book_id_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    NO CYCLE
    CACHE 1;

-- AUTHOR ID
CREATE SEQUENCE auth_id_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    NO CYCLE
    CACHE 1;

-- PUBLISHER ID
CREATE SEQUENCE pub_id_seq
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    NO CYCLE
    CACHE 1;
